# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'app1-python'
    static_configs:
      - targets: ['app1:5000']
    metrics_path: /metrics

  - job_name: 'app2-node'
    static_configs:
      - targets: ['app2:3000']
    metrics_path: /metrics

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: /nginx_status
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'nginx_.*'
        action: keep

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']